[package]
name = "busan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5"
prost = "0.11"
prost-types = "0.11"



## --------------------------------------------------------------------------------
## Examples

[[bin]]
name = "hello_world"
path = "examples/hello_world/main.rs"