name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # Cancel previous actions from the same PR: https://stackoverflow.com/a/72408109
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spell_check:
    name: Spell Check
    runs-on: ubuntu-latest
    needs: [check]
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install CSpell
        run: npm install -g cspell
      - uses: actions/checkout@v4
      - name: Markdown Spellcheck
        run: cspell --config .github/workflows/cspell.json "**/*.md"
